// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: delivery/v1/deliveryReporter.proto

package deliveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_SUCCESS     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_RETRYING    DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_DEAD_LETTER DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_SUCCESS",
		2: "DELIVERY_STATUS_FAILED",
		3: "DELIVERY_STATUS_RETRYING",
		4: "DELIVERY_STATUS_DEAD_LETTER",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_SUCCESS":     1,
		"DELIVERY_STATUS_FAILED":      2,
		"DELIVERY_STATUS_RETRYING":    3,
		"DELIVERY_STATUS_DEAD_LETTER": 4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_v1_deliveryReporter_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_delivery_v1_deliveryReporter_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_delivery_v1_deliveryReporter_proto_rawDescGZIP(), []int{0}
}

type ReportAttemptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EndpointId      string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	AttemptNumber   int32                  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Status          DeliveryStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=delivery.v1.DeliveryStatus" json:"status,omitempty"` // SUCCESS, FAILED, RETRYING
	HttpStatusCode  int32                  `protobuf:"varint,5,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	ExecutionTimeMs int32                  `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	ResponseBody    string                 `protobuf:"bytes,7,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TraceId         string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportAttemptRequest) Reset() {
	*x = ReportAttemptRequest{}
	mi := &file_delivery_v1_deliveryReporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttemptRequest) ProtoMessage() {}

func (x *ReportAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_deliveryReporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttemptRequest.ProtoReflect.Descriptor instead.
func (*ReportAttemptRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_deliveryReporter_proto_rawDescGZIP(), []int{0}
}

func (x *ReportAttemptRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReportAttemptRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ReportAttemptRequest) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *ReportAttemptRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *ReportAttemptRequest) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

func (x *ReportAttemptRequest) GetExecutionTimeMs() int32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *ReportAttemptRequest) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *ReportAttemptRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportAttemptRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ReportAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAttemptResponse) Reset() {
	*x = ReportAttemptResponse{}
	mi := &file_delivery_v1_deliveryReporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttemptResponse) ProtoMessage() {}

func (x *ReportAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_deliveryReporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttemptResponse.ProtoReflect.Descriptor instead.
func (*ReportAttemptResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_deliveryReporter_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAttemptResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_delivery_v1_deliveryReporter_proto protoreflect.FileDescriptor

const file_delivery_v1_deliveryReporter_proto_rawDesc = "" +
	"\n" +
	"\"delivery/v1/deliveryReporter.proto\x12\vdelivery.v1\"\xe9\x02\n" +
	"\x14ReportAttemptRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x05R\rattemptNumber\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.delivery.v1.DeliveryStatusR\x06status\x12(\n" +
	"\x10http_status_code\x18\x05 \x01(\x05R\x0ehttpStatusCode\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x05R\x0fexecutionTimeMs\x12#\n" +
	"\rresponse_body\x18\a \x01(\tR\fresponseBody\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\";\n" +
	"\x15ReportAttemptResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*\xa9\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_SUCCESS\x10\x01\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x02\x12\x1c\n" +
	"\x18DELIVERY_STATUS_RETRYING\x10\x03\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_DEAD_LETTER\x10\x042q\n" +
	"\x17DeliveryReporterService\x12V\n" +
	"\rReportAttempt\x12!.delivery.v1.ReportAttemptRequest\x1a\".delivery.v1.ReportAttemptResponseBIZGgithub.com/Venamuss/webhook-dispatcher/api/proto/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_deliveryReporter_proto_rawDescOnce sync.Once
	file_delivery_v1_deliveryReporter_proto_rawDescData []byte
)

func file_delivery_v1_deliveryReporter_proto_rawDescGZIP() []byte {
	file_delivery_v1_deliveryReporter_proto_rawDescOnce.Do(func() {
		file_delivery_v1_deliveryReporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_deliveryReporter_proto_rawDesc), len(file_delivery_v1_deliveryReporter_proto_rawDesc)))
	})
	return file_delivery_v1_deliveryReporter_proto_rawDescData
}

var file_delivery_v1_deliveryReporter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_delivery_v1_deliveryReporter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delivery_v1_deliveryReporter_proto_goTypes = []any{
	(DeliveryStatus)(0),           // 0: delivery.v1.DeliveryStatus
	(*ReportAttemptRequest)(nil),  // 1: delivery.v1.ReportAttemptRequest
	(*ReportAttemptResponse)(nil), // 2: delivery.v1.ReportAttemptResponse
}
var file_delivery_v1_deliveryReporter_proto_depIdxs = []int32{
	0, // 0: delivery.v1.ReportAttemptRequest.status:type_name -> delivery.v1.DeliveryStatus
	1, // 1: delivery.v1.DeliveryReporterService.ReportAttempt:input_type -> delivery.v1.ReportAttemptRequest
	2, // 2: delivery.v1.DeliveryReporterService.ReportAttempt:output_type -> delivery.v1.ReportAttemptResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_delivery_v1_deliveryReporter_proto_init() }
func file_delivery_v1_deliveryReporter_proto_init() {
	if File_delivery_v1_deliveryReporter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_deliveryReporter_proto_rawDesc), len(file_delivery_v1_deliveryReporter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_v1_deliveryReporter_proto_goTypes,
		DependencyIndexes: file_delivery_v1_deliveryReporter_proto_depIdxs,
		EnumInfos:         file_delivery_v1_deliveryReporter_proto_enumTypes,
		MessageInfos:      file_delivery_v1_deliveryReporter_proto_msgTypes,
	}.Build()
	File_delivery_v1_deliveryReporter_proto = out.File
	file_delivery_v1_deliveryReporter_proto_goTypes = nil
	file_delivery_v1_deliveryReporter_proto_depIdxs = nil
}
