// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: delivery/v1/deliveryReporter.proto

package deliveryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryReporterService_ReportAttempt_FullMethodName = "/delivery.v1.DeliveryReporterService/ReportAttempt"
)

// DeliveryReporterServiceClient is the client API for DeliveryReporterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryReporterServiceClient interface {
	// Асинхронная фиксация статуса отправки из Dispatcher в базу Subscription API
	ReportAttempt(ctx context.Context, in *ReportAttemptRequest, opts ...grpc.CallOption) (*ReportAttemptResponse, error)
}

type deliveryReporterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryReporterServiceClient(cc grpc.ClientConnInterface) DeliveryReporterServiceClient {
	return &deliveryReporterServiceClient{cc}
}

func (c *deliveryReporterServiceClient) ReportAttempt(ctx context.Context, in *ReportAttemptRequest, opts ...grpc.CallOption) (*ReportAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAttemptResponse)
	err := c.cc.Invoke(ctx, DeliveryReporterService_ReportAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryReporterServiceServer is the server API for DeliveryReporterService service.
// All implementations must embed UnimplementedDeliveryReporterServiceServer
// for forward compatibility.
type DeliveryReporterServiceServer interface {
	// Асинхронная фиксация статуса отправки из Dispatcher в базу Subscription API
	ReportAttempt(context.Context, *ReportAttemptRequest) (*ReportAttemptResponse, error)
	mustEmbedUnimplementedDeliveryReporterServiceServer()
}

// UnimplementedDeliveryReporterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryReporterServiceServer struct{}

func (UnimplementedDeliveryReporterServiceServer) ReportAttempt(context.Context, *ReportAttemptRequest) (*ReportAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAttempt not implemented")
}
func (UnimplementedDeliveryReporterServiceServer) mustEmbedUnimplementedDeliveryReporterServiceServer() {
}
func (UnimplementedDeliveryReporterServiceServer) testEmbeddedByValue() {}

// UnsafeDeliveryReporterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryReporterServiceServer will
// result in compilation errors.
type UnsafeDeliveryReporterServiceServer interface {
	mustEmbedUnimplementedDeliveryReporterServiceServer()
}

func RegisterDeliveryReporterServiceServer(s grpc.ServiceRegistrar, srv DeliveryReporterServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryReporterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryReporterService_ServiceDesc, srv)
}

func _DeliveryReporterService_ReportAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryReporterServiceServer).ReportAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryReporterService_ReportAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryReporterServiceServer).ReportAttempt(ctx, req.(*ReportAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryReporterService_ServiceDesc is the grpc.ServiceDesc for DeliveryReporterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryReporterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.v1.DeliveryReporterService",
	HandlerType: (*DeliveryReporterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportAttempt",
			Handler:    _DeliveryReporterService_ReportAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery/v1/deliveryReporter.proto",
}
