syntax = "proto3";

package delivery.v1;
option go_package = "github.com/Venamuss/webhook-dispatcher/api/proto/delivery/v1;deliveryv1";

service DeliveryReporterService {
  // Асинхронная фиксация статуса отправки из Dispatcher в базу Subscription API
  rpc ReportAttempt (ReportAttemptRequest) returns (ReportAttemptResponse);
}

message ReportAttemptRequest {
  string event_id = 1;
  string endpoint_id = 2;
  int32 attempt_number = 3;
  string status = 4;                 // SUCCESS, FAILED, RETRYING
  int32 http_status_code = 5;
  int32 execution_time_ms = 6;
  string response_body = 7;
  string error_message = 8;
  string trace_id = 9;
}

message ReportAttemptResponse {
  bool acknowledged = 1;
}