// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: event/v1/eventGateway.proto

package eventv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestionService_PublishEvent_FullMethodName = "/event.v1.EventIngestionService/PublishEvent"
	EventIngestionService_PublishBatch_FullMethodName = "/event.v1.EventIngestionService/PublishBatch"
)

// EventIngestionServiceClient is the client API for EventIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngestionServiceClient interface {
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
	PublishBatch(ctx context.Context, in *PublishBatchRequest, opts ...grpc.CallOption) (*PublishBatchResponse, error)
}

type eventIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionServiceClient(cc grpc.ClientConnInterface) EventIngestionServiceClient {
	return &eventIngestionServiceClient{cc}
}

func (c *eventIngestionServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, EventIngestionService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionServiceClient) PublishBatch(ctx context.Context, in *PublishBatchRequest, opts ...grpc.CallOption) (*PublishBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishBatchResponse)
	err := c.cc.Invoke(ctx, EventIngestionService_PublishBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventIngestionServiceServer is the server API for EventIngestionService service.
// All implementations must embed UnimplementedEventIngestionServiceServer
// for forward compatibility.
type EventIngestionServiceServer interface {
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	PublishBatch(context.Context, *PublishBatchRequest) (*PublishBatchResponse, error)
	mustEmbedUnimplementedEventIngestionServiceServer()
}

// UnimplementedEventIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServiceServer struct{}

func (UnimplementedEventIngestionServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedEventIngestionServiceServer) PublishBatch(context.Context, *PublishBatchRequest) (*PublishBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishBatch not implemented")
}
func (UnimplementedEventIngestionServiceServer) mustEmbedUnimplementedEventIngestionServiceServer() {}
func (UnimplementedEventIngestionServiceServer) testEmbeddedByValue()                               {}

// UnsafeEventIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServiceServer will
// result in compilation errors.
type UnsafeEventIngestionServiceServer interface {
	mustEmbedUnimplementedEventIngestionServiceServer()
}

func RegisterEventIngestionServiceServer(s grpc.ServiceRegistrar, srv EventIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedEventIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestionService_ServiceDesc, srv)
}

func _EventIngestionService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestionService_PublishBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).PublishBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_PublishBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).PublishBatch(ctx, req.(*PublishBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventIngestionService_ServiceDesc is the grpc.ServiceDesc for EventIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.v1.EventIngestionService",
	HandlerType: (*EventIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishEvent",
			Handler:    _EventIngestionService_PublishEvent_Handler,
		},
		{
			MethodName: "PublishBatch",
			Handler:    _EventIngestionService_PublishBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event/v1/eventGateway.proto",
}
