// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: event/v1/eventGateway.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishStatus int32

const (
	PublishStatus_PUBLISH_STATUS_UNSPECIFIED PublishStatus = 0
	PublishStatus_PUBLISH_STATUS_ACCEPTED    PublishStatus = 1
	PublishStatus_PUBLISH_STATUS_QUEUED      PublishStatus = 2
)

// Enum value maps for PublishStatus.
var (
	PublishStatus_name = map[int32]string{
		0: "PUBLISH_STATUS_UNSPECIFIED",
		1: "PUBLISH_STATUS_ACCEPTED",
		2: "PUBLISH_STATUS_QUEUED",
	}
	PublishStatus_value = map[string]int32{
		"PUBLISH_STATUS_UNSPECIFIED": 0,
		"PUBLISH_STATUS_ACCEPTED":    1,
		"PUBLISH_STATUS_QUEUED":      2,
	}
)

func (x PublishStatus) Enum() *PublishStatus {
	p := new(PublishStatus)
	*p = x
	return p
}

func (x PublishStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_eventGateway_proto_enumTypes[0].Descriptor()
}

func (PublishStatus) Type() protoreflect.EnumType {
	return &file_event_v1_eventGateway_proto_enumTypes[0]
}

func (x PublishStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStatus.Descriptor instead.
func (PublishStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{0}
}

type EventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                                              // Уникальный ID события (для идемпотентности)
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                           // ID тенанта
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                        // Тип события (e.g. order.created)
	DataJson      []byte                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`                                                           // Raw JSON тела события
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Метаданные и кастомные заголовки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPayload) Reset() {
	*x = EventPayload{}
	mi := &file_event_v1_eventGateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPayload) ProtoMessage() {}

func (x *EventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_eventGateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPayload.ProtoReflect.Descriptor instead.
func (*EventPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{0}
}

func (x *EventPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventPayload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventPayload) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *EventPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventPayload          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_event_v1_eventGateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_eventGateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEventRequest) GetEvent() *EventPayload {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        PublishStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=event.v1.PublishStatus" json:"status,omitempty"` // ACCEPTED / QUEUED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_event_v1_eventGateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_eventGateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{2}
}

func (x *PublishEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishEventResponse) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PUBLISH_STATUS_UNSPECIFIED
}

type PublishBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventPayload        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_event_v1_eventGateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_eventGateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBatchRequest) GetEvents() []*EventPayload {
	if x != nil {
		return x.Events
	}
	return nil
}

type BatchItemError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchItemError) Reset() {
	*x = BatchItemError{}
	mi := &file_event_v1_eventGateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchItemError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchItemError) ProtoMessage() {}

func (x *BatchItemError) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_eventGateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchItemError.ProtoReflect.Descriptor instead.
func (*BatchItemError) Descriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{4}
}

func (x *BatchItemError) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BatchItemError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BatchItemError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	FailedItems   []*BatchItemError      `protobuf:"bytes,3,rep,name=failed_items,json=failedItems,proto3" json:"failed_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResponse) Reset() {
	*x = PublishBatchResponse{}
	mi := &file_event_v1_eventGateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResponse) ProtoMessage() {}

func (x *PublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_eventGateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResponse.ProtoReflect.Descriptor instead.
func (*PublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_eventGateway_proto_rawDescGZIP(), []int{5}
}

func (x *PublishBatchResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *PublishBatchResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *PublishBatchResponse) GetFailedItems() []*BatchItemError {
	if x != nil {
		return x.FailedItems
	}
	return nil
}

var File_event_v1_eventGateway_proto protoreflect.FileDescriptor

const file_event_v1_eventGateway_proto_rawDesc = "" +
	"\n" +
	"\x1bevent/v1/eventGateway.proto\x12\bevent.v1\"\x81\x02\n" +
	"\fEventPayload\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\fR\bdataJson\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.event.v1.EventPayload.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x13PublishEventRequest\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.event.v1.EventPayloadR\x05event\"b\n" +
	"\x14PublishEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.event.v1.PublishStatusR\x06status\"E\n" +
	"\x13PublishBatchRequest\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.event.v1.EventPayloadR\x06events\"d\n" +
	"\x0eBatchItemError\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9d\x01\n" +
	"\x14PublishBatchResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12;\n" +
	"\ffailed_items\x18\x03 \x03(\v2\x18.event.v1.BatchItemErrorR\vfailedItems*g\n" +
	"\rPublishStatus\x12\x1e\n" +
	"\x1aPUBLISH_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PUBLISH_STATUS_ACCEPTED\x10\x01\x12\x19\n" +
	"\x15PUBLISH_STATUS_QUEUED\x10\x022\xb5\x01\n" +
	"\x15EventIngestionService\x12M\n" +
	"\fPublishEvent\x12\x1d.event.v1.PublishEventRequest\x1a\x1e.event.v1.PublishEventResponse\x12M\n" +
	"\fPublishBatch\x12\x1d.event.v1.PublishBatchRequest\x1a\x1e.event.v1.PublishBatchResponseBCZAgithub.com/Venamuss/webhook-dispatcher/api/proto/event/v1;eventv1b\x06proto3"

var (
	file_event_v1_eventGateway_proto_rawDescOnce sync.Once
	file_event_v1_eventGateway_proto_rawDescData []byte
)

func file_event_v1_eventGateway_proto_rawDescGZIP() []byte {
	file_event_v1_eventGateway_proto_rawDescOnce.Do(func() {
		file_event_v1_eventGateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_eventGateway_proto_rawDesc), len(file_event_v1_eventGateway_proto_rawDesc)))
	})
	return file_event_v1_eventGateway_proto_rawDescData
}

var file_event_v1_eventGateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_v1_eventGateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_event_v1_eventGateway_proto_goTypes = []any{
	(PublishStatus)(0),           // 0: event.v1.PublishStatus
	(*EventPayload)(nil),         // 1: event.v1.EventPayload
	(*PublishEventRequest)(nil),  // 2: event.v1.PublishEventRequest
	(*PublishEventResponse)(nil), // 3: event.v1.PublishEventResponse
	(*PublishBatchRequest)(nil),  // 4: event.v1.PublishBatchRequest
	(*BatchItemError)(nil),       // 5: event.v1.BatchItemError
	(*PublishBatchResponse)(nil), // 6: event.v1.PublishBatchResponse
	nil,                          // 7: event.v1.EventPayload.MetadataEntry
}
var file_event_v1_eventGateway_proto_depIdxs = []int32{
	7, // 0: event.v1.EventPayload.metadata:type_name -> event.v1.EventPayload.MetadataEntry
	1, // 1: event.v1.PublishEventRequest.event:type_name -> event.v1.EventPayload
	0, // 2: event.v1.PublishEventResponse.status:type_name -> event.v1.PublishStatus
	1, // 3: event.v1.PublishBatchRequest.events:type_name -> event.v1.EventPayload
	5, // 4: event.v1.PublishBatchResponse.failed_items:type_name -> event.v1.BatchItemError
	2, // 5: event.v1.EventIngestionService.PublishEvent:input_type -> event.v1.PublishEventRequest
	4, // 6: event.v1.EventIngestionService.PublishBatch:input_type -> event.v1.PublishBatchRequest
	3, // 7: event.v1.EventIngestionService.PublishEvent:output_type -> event.v1.PublishEventResponse
	6, // 8: event.v1.EventIngestionService.PublishBatch:output_type -> event.v1.PublishBatchResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_event_v1_eventGateway_proto_init() }
func file_event_v1_eventGateway_proto_init() {
	if File_event_v1_eventGateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_eventGateway_proto_rawDesc), len(file_event_v1_eventGateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_v1_eventGateway_proto_goTypes,
		DependencyIndexes: file_event_v1_eventGateway_proto_depIdxs,
		EnumInfos:         file_event_v1_eventGateway_proto_enumTypes,
		MessageInfos:      file_event_v1_eventGateway_proto_msgTypes,
	}.Build()
	File_event_v1_eventGateway_proto = out.File
	file_event_v1_eventGateway_proto_goTypes = nil
	file_event_v1_eventGateway_proto_depIdxs = nil
}
